[package]
name = "typst-note"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["Linyu Yang"]
license = "MIT"
description = "A proof of concept library for commutative diagrams."
# repository = "https://gitlab.com/"
